"""sync

Revision ID: 033923554633
Revises: fef011e7c80c
Create Date: 2026-03-28 14:32:39.439584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '033923554633'
down_revision: Union[str, Sequence[str], None] = 'fef011e7c80c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failed_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_name', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # op.drop_table('spatial_ref_sys')
    op.add_column('disaster_events', sa.Column('review_deadline', sa.DateTime(timezone=True), nullable=True))
    op.add_column('disaster_events', sa.Column('decision_log', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True))
    op.add_column('disaster_events', sa.Column('vision_status', sa.String(length=50), nullable=True))
    op.create_index('ix_disaster_events_decision_log', 'disaster_events', ['decision_log'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_disaster_events_decision_log', table_name='disaster_events', postgresql_using='gin')
    op.drop_column('disaster_events', 'vision_status')
    op.drop_column('disaster_events', 'decision_log')
    op.drop_column('disaster_events', 'review_deadline')
    # op.create_table('spatial_ref_sys', ...)
    op.drop_table('failed_jobs')
    # ### end Alembic commands ###
