""" add_override_fields

Revision ID: 993e2b91ef23
Revises: b27c24e82a9a
Create Date: 2026-02-23 18:46:27.338266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '993e2b91ef23'
down_revision: Union[str, Sequence[str], None] = 'b27c24e82a9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.add_column('disaster_events', sa.Column('override_lat', sa.Float(), nullable=True))
    op.add_column('disaster_events', sa.Column('override_lng', sa.Float(), nullable=True))
    op.add_column('disaster_events', sa.Column('override_timestamp', sa.DateTime(timezone=True), nullable=True))
    op.add_column('disaster_events', sa.Column('is_location_overridden', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('disaster_events', 'is_location_overridden')
    op.drop_column('disaster_events', 'override_timestamp')
    op.drop_column('disaster_events', 'override_lng')
    op.drop_column('disaster_events', 'override_lat')
    # spatial_ref_sys is managed by PostGIS
    # ### end Alembic commands ###
