""" add_confidence_and_user_prep_fields

Revision ID: e7818c12c656
Revises: 993e2b91ef23
Create Date: 2026-02-23 19:16:09.766115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'e7818c12c656'
down_revision: Union[str, Sequence[str], None] = '993e2b91ef23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.add_column('disaster_events', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('emergency_contact', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('home_location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.add_column('users', sa.Column('medical_conditions', sa.Text(), nullable=True))
    # op.create_index('idx_users_home_location', 'users', ['home_location'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('idx_users_home_location', table_name='users', postgresql_using='gist')
    op.drop_column('users', 'medical_conditions')
    op.drop_column('users', 'home_location')
    op.drop_column('users', 'emergency_contact')
    op.drop_column('users', 'phone')
    op.drop_column('disaster_events', 'confidence_score')
    # spatial_ref_sys managed by postgis
    # ### end Alembic commands ###
