"""Add RescueUnit model

Revision ID: fef011e7c80c
Revises: e7818c12c656
Create Date: 2026-03-21 18:20:52.804152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'fef011e7c80c'
down_revision: Union[str, Sequence[str], None] = 'e7818c12c656'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    if 'rescue_units' not in inspector.get_table_names():
        # ### commands auto generated by Alembic - please adjust! ###
        op.create_table('rescue_units',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('callsign', sa.String(length=100), nullable=False),
        sa.Column('unit_type', sa.String(50), nullable=False),
        sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
        sa.Column('status', sa.String(50), nullable=True),
        sa.Column('last_active_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('callsign')
        )
        op.create_index('idx_rescue_units_location', 'rescue_units', ['location'], unique=False, postgresql_using='gist')
        op.create_index(op.f('ix_rescue_units_status'), 'rescue_units', ['status'], unique=False)
        # ### end Alembic commands ###
    else:
        print("[ALEMBIC] Table 'rescue_units' already exists. Skipping creation.")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.drop_index(op.f('ix_rescue_units_status'), table_name='rescue_units')
    op.drop_index('idx_rescue_units_location', table_name='rescue_units', postgresql_using='gist')
    op.drop_table('rescue_units')
    # ### end Alembic commands ###
